Repository aman34503/Go-Airbnb, pull requests merged in 2022-02, with the labels that each got.

#14 Updated : Readme
  README.md
Labels: documentation, easy, jwoc

#31 #29- Modified the home page banner foe better UI
  package-lock.json
  src/Banner.css
  src/Banner.js
  src/banner.jpg
Labels: jwoc, medium

#35 Login
  public/index.html
  src/App.js
  src/Header.css
  src/Header.js
  src/login.css
  src/login.jsx
  src/login.svg
Labels: jwoc, hard

#38 Home Page responsiveness
  package-lock.json
  src/App.css
  src/Banner.css
  src/Card.css
  src/Footer.css
  src/Header.css
  src/Home.css
Labels: jwoc, hard
